### ISSUE TITLE
The DLib update and requires at least OpenCV 3~

### ISSUE THREAD

**Issue by kingsleynuaa** [mp3guy/Kintinuous#10]
the details can be seen at https://github.com/dorian3d/DLib/issues/7

**Comment by kingsleynuaa** [comment]
@mp3guy @zry656565 @johnbmcd 
I have fix the build.sh to work with the OpenCV 3.1.0 and it work well before the last command: line 124 ,make -j8
There are errors like that: 
```sh
Kintinuous/src/backend/DBowInterfaceSurf.h:26:42: fatal error: opencv2/nonfree/features2d.hpp: No such file or directory
```
and I change the DBowInterfaceSurf.h 
like that:
```sh
#include <opencv2/features2d.hpp>
```

but other errors happened:
```sh
Kintinuous/src/backend/DBowInterfaceSurf.cpp: In member function ‘void DBowInterfaceSurf::detectSURF(const cv::Mat&, std::vector<float>&, std::vector<cv::KeyPoint>&)’:
/home/kingsley/work/Kintinuous/src/backend/DBowInterfaceSurf.cpp:75:12: error: ‘SURF’ in namespace ‘cv’ does not name a type
     static cv::SURF surf_detector(400, 4, 2, false);
            ^
/home/kingsley/work/Kintinuous/src/backend/DBowInterfaceSurf.cpp:78:45: error: ‘surf_detector’ was not declared in this scope
     surf_detector(im, cv::Mat(), keys, plain);
```

maybe there are something did't work well with the   DBow?

I am not familiar with the source code, Could you please help me?
Thank you very much!

**Comment by kingsleynuaa** [comment]
@mp3guy I have updated to work with OpenCV 3.1.0, and it works very well before but there are still some problems with the file:
Kintinuous/src/backend/DBowInterfaceSurf.h
```sh
 opencv2/nonfree/features2d.hpp: No such file or directory
```

and after change it to the
```sh
 #include <opencv2/features2d.hpp>
```

or 

```sh
 #include <opencv2/features2d/features2d.hpp>
```

there are still some problems:
```sh
Kintinuous/src/backend/DBowInterfaceSurf.cpp: In member function ‘void DBowInterfaceSurf::detectSURF(const cv::Mat&, std::vector<float>&, std::vector<cv::KeyPoint>&)’:
/home/kingsley/work/Kintinuous/src/backend/DBowInterfaceSurf.cpp:75:12: error: ‘SURF’ in namespace ‘cv’ does not name a type
     static cv::SURF surf_detector(400, 4, 2, false);
            ^
/home/kingsley/work/Kintinuous/src/backend/DBowInterfaceSurf.cpp:78:45: error: ‘surf_detector’ was not declared in this scope
     surf_detector(im, cv::Mat(), keys, plain);
```

Please help me~ Thank you very much!

**Comment by mp3guy** [comment]
Fixed in abd79c2f6253b6a12c0e5cfb190a5d01787ff154l; Simply use the revisions before OpenCV3 was introduced.

**Comment by quanqhow** [comment]
I installed the OpenCV 3.1 in Ubuntu 16.04.2, and other dependencies,there are also the same bug for me : 
`Kintinuous/src/backend/DBowInterfaceSurf.h:26:42: fatal error: opencv2/nonfree/features2d.hpp: No such file or directory `
How did you solve this problem? May you explain it in detail.

**Comment by quanqhow** [comment]
@kingsleynuaa  I also encountered this problem, did you solve this issue? Could you give me some suggestion?
`Kintinuous/src/backend/DBowInterfaceSurf.h:26:42: fatal error: opencv2/nonfree/features2d.hpp: No such file or directory`

**Comment by mp3guy** [comment]
Don't use OpenCV 3.1 for Kintinuous, it hasn't been built to support it.

**Comment by quanqhow** [comment]
Thank you very much for your reply. I also got trouble in other issues. I
execute the code:  ./ElasticFusion -l dyson_lab.klg
I watched all of this demo, but I didn't find where the saved map is.
Moreover, I cannot zoom in or zoom out and cannot rotate the map in the
Pangolin window. Could yo help me?

Best,
Albert

2017-03-27 21:27 GMT+08:00 Thomas Whelan <notifications@github.com>:
